export const DIMENSION_LABELS = {
  widthInches: 'Width',
  depthInches: 'Depth',
  heightInches: 'Height',
  leftReturnInches: 'Left clipped corner',
  rightReturnInches: 'Right clipped corner',
  leftAngleCutInches: 'Left angle cut',
  rightAngleCutInches: 'Right angle cut',
  frontRadiusInches: 'Front radius',
  radiusDepthInches: 'Radius depth',
  mantelWidthInches: 'Mantel width',
  mantelDepthInches: 'Mantel depth',
  mantelHeightInches: 'Mantel height',
  surroundFaceWidthInches: 'Surround face width',
  surroundFaceHeightInches: 'Surround face height',
  openingWidthInches: 'Opening width',
  openingHeightInches: 'Opening height',
  sideReturnInches: 'Side return',
  capShelfWidthInches: 'Cap/shelf width',
  capShelfDepthInches: 'Cap/shelf depth',
  pieceDescription: 'Piece description',
  pieceWidthInches: 'Piece width',
  pieceDepthInches: 'Piece depth',
  quantity: 'Quantity',
  installLocation: 'Install location',
  corbelQuantity: 'Corbel quantity',
  corbelWidthInches: 'Corbel width',
  corbelDepthInches: 'Corbel depth',
  corbelHeightInches: 'Corbel height',
  angleNotes: 'Angle notes / degrees',
  radiusNotes: 'Radius / arc notes',
  supportNotes: 'Support / pocket notes',
  mantelEdgeNotes: 'Mantel edge notes',
  seamNotes: 'Seam notes',
  spacingNotes: 'Spacing / centering notes',
  inventoryNotes: 'Inventory usage notes',
}

export const DIMENSION_FIELD_TYPES = {
  pieceDescription: 'text',
  installLocation: 'text',
  angleNotes: 'textarea',
  radiusNotes: 'textarea',
  supportNotes: 'textarea',
  mantelEdgeNotes: 'textarea',
  seamNotes: 'textarea',
  spacingNotes: 'textarea',
  inventoryNotes: 'textarea',
}

export const REQUIRED_CHECKBOXES = [
  'Field measure confirmed',
  'Material sample approved',
  'Finish confirmed',
  'Edge confirmed',
  'Price reviewed',
  'Customer signed',
  'Ready for shop',
  'Shop accepted',
]

export const SIGNATURE_LINES = [
  'Customer approval',
  'Salesperson',
  'Manager/pricing review',
  'Shop review',
]

export const FUTURE_PRINT_FORM_LABELS = {
  hearth_order: 'Hearth Order Form',
  hearth_clipped_corners: 'Hearth with Clipped Corners Form',
  hearth_angle_cuts: 'Hearth with Angle Cuts Form',
  hearth_radius_front: 'Hearth with Radius Front Form',
  hearth_mantel: 'Hearth + Mantel Form',
  fp_hearth_surround: 'Fireplace Hearth + Surround Form',
  cap_shelf_slab: 'Cap / Shelf / Slab Piece Form',
  corbels_mantel: 'Corbels & Mantel Form',
  material_selection_approval: 'Material Selection / Approval Form',
  custom_stone_shop: 'Generic Custom Stone Shop Form',
  limestone_inventory_usage_log: 'Limestone Inventory Usage Log',
}
